---
output: 
  pdf_document:
    latex_engine: pdflatex
    template: ~/Documents/Resume_CV/cover_letter_3.tex
geometry: margin=1in

title: "CV"
author: Jonathan Nguyen

jobtitle: "Business Office Supervisor"
address: "1813 Oakbranch Dr., Pearland TX, 77581"
fontawesome: yes
email: Jon.P.Nguyen@pm.me 
gitlab: jonguyen 
phone: "(713) 557-3595"
updated: no

keywords: R Markdown, academic CV, template

fontfamily: mathpazo
fontfamilyoptions: sc, osf
fontsize: 11pt
linkcolor: blue
urlcolor: blue
---

# Education

* B.S. Computer Science (In Progress) - Western Governors University
* A.S. Computer Science (2017) - San Jacinto College
* A.A. General Studies (2017) - San Jacinto College

# Employment

## San Jacinto College

Business Office Supervisor \hfill 10/20 - Present

> A management position that includes duties such as vault auditing, mass student reporting, managing staff, and various projects as needed. Other duties include cashiering, daily reports, and handling student concerns.

Records Specialist \hfill 02/16 - 10/20 

> The job duties included processing electronic transcripts, evaluations, and special projects. Other duties consisted of writing scripts, streamlining work processes, and increasing productivity.

Student Account Specialist \hfill 06/14 - 04/16 

> The duties of the role were fulfilling payment contracts, managing the cash drawer, processing student payment transactions, and running reports for other offices in the college.   

# Certifications

* CompTia Project+

# Knowledge

*Programming Languages*  

* Medium: Autohotkey, Python, Markdown, Java
* Novice: SQL

# References

Ryder Bush - (805) 368-0743  
Sherry Gray - (832) 621-7040  
Barbara Ewell - (281) 731-6586
